# Generated by Django 3.1.3 on 2023-05-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'schools'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'users'},
        ),
    ]
