# Generated by Django 3.1.3 on 2023-05-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230501_1206'),
        ('users', '0003_auto_20230430_1844'),
    ]

    operations = [
    ]
