# Generated by Django 3.1.3 on 2023-06-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0020_auto_20230619_0019'),
        ('login', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('levelCurrent', models.CharField(blank=True, max_length=200, null=True)),
                ('levelRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('levelGap', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacity')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityXEmployee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('levelCurrent', models.CharField(blank=True, max_length=200, null=True)),
                ('levelRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('levelGap', models.IntegerField(blank=True, null=True)),
                ('likeness', models.FloatField(blank=True, null=True)),
                ('hasCertificate', models.BooleanField(default=False)),
                ('registerByEmployee', models.BooleanField(default=False)),
                ('requiredForPosition', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacity')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityXAreaXPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('levelRequired', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.area')),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacity')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.position')),
            ],
        ),
        migrations.CreateModel(
            name='CapacityType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('upperType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacitytype')),
            ],
        ),
        migrations.AddField(
            model_name='capacity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacitytype'),
        ),
    ]
