# Generated by Django 3.1.3 on 2023-06-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceXAreaXPosition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('levelRequired', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceXEmployee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('levelCurrent', models.IntegerField(blank=True, null=True)),
                ('levelRequired', models.IntegerField(blank=True, null=True)),
                ('levelGap', models.IntegerField(blank=True, null=True)),
                ('likeness', models.FloatField(blank=True, null=True)),
                ('hasCertificate', models.BooleanField(default=False)),
                ('registerByEmployee', models.BooleanField(default=False)),
                ('requiredForPosition', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('levelCurrent', models.IntegerField(blank=True, null=True)),
                ('levelRequired', models.IntegerField(blank=True, null=True)),
                ('levelGap', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.competence')),
            ],
        ),
    ]
