# Generated by Django 3.1.3 on 2023-06-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('login', '0001_initial'),
        ('gaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingneed',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='competencexemployee',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.competence'),
        ),
        migrations.AddField(
            model_name='competencexemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='competencexareaxposition',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.area'),
        ),
        migrations.AddField(
            model_name='competencexareaxposition',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.competence'),
        ),
        migrations.AddField(
            model_name='competencexareaxposition',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.position'),
        ),
        migrations.AddField(
            model_name='competencetype',
            name='upperType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaps.competencetype'),
        ),
        migrations.AddField(
            model_name='competence',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.competencetype'),
        ),
    ]
