# Generated by Django 3.1.3 on 2023-07-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaps', '0001_initial'),
        ('personal', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingneed',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='capacityxemployee',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacity'),
        ),
        migrations.AddField(
            model_name='capacityxemployee',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='capacityxareaxposition',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacity'),
        ),
        migrations.AddField(
            model_name='capacityxareaxposition',
            name='positionArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion'),
        ),
        migrations.AddField(
            model_name='capacitytype',
            name='upperType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacitytype'),
        ),
        migrations.AddField(
            model_name='capacity',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gaps.capacitytype'),
        ),
    ]
