# Generated by Django 3.1.3 on 2023-05-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('firstName', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('maidenName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=46, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='login.role')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('isSupervisor', models.BooleanField()),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.employee')),
            ],
        ),
    ]
