# Generated by Django 3.1.3 on 2023-05-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0003_auto_20230501_1324'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.area'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.position'),
        ),
    ]
