# Generated by Django 3.1.3 on 2023-05-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230501_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
