# Generated by Django 3.1.3 on 2023-05-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20230523_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='maidenName',
            new_name='maiden_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='secondName',
            new_name='second_name',
        ),
    ]
