# Generated by Django 3.1.3 on 2023-05-04 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaxPosicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('availableQuantity', models.IntegerField()),
                ('unavailableQuantity', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.area')),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('isSupervisor', models.BooleanField()),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.area')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('requirements', models.CharField(blank=True, max_length=500, null=True)),
                ('publicationDate', models.DateField(blank=True, null=True)),
                ('selectionStartDate', models.DateField(blank=True, null=True)),
                ('selectionFinishDate', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('benefits', models.TextField(blank=True, default='')),
                ('responsabilities', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('tipoJornada', models.TextField(blank=True, default='')),
                ('modalidadTrabajo', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField()),
                ('modifiedDate', models.DateField()),
                ('isActive', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('firstName', models.CharField(max_length=25)),
                ('secondName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('maidenName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=46, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('cv', models.TextField(blank=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='offers.role')),
            ],
        ),
        migrations.CreateModel(
            name='OfferNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('jobOffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.joboffer')),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('jobOffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.joboffer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.user')),
            ],
        ),
        migrations.AddField(
            model_name='joboffer',
            name='candidates',
            field=models.ManyToManyField(through='offers.JobOfferxUser', to='offers.User'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.areaxposicion'),
        ),
        migrations.CreateModel(
            name='EmployeexCompetency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.competency')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='competencies',
            field=models.ManyToManyField(through='offers.EmployeexCompetency', to='offers.Competency'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.employee'),
        ),
        migrations.AddField(
            model_name='competency',
            name='typeComp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.competencytype'),
        ),
        migrations.CreateModel(
            name='AreaxPositionxCompetency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.competency')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.areaxposicion')),
            ],
        ),
        migrations.AddField(
            model_name='areaxposicion',
            name='competencies',
            field=models.ManyToManyField(through='offers.AreaxPositionxCompetency', to='offers.Competency'),
        ),
        migrations.AddField(
            model_name='areaxposicion',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.position'),
        ),
        migrations.AddField(
            model_name='area',
            name='roles',
            field=models.ManyToManyField(through='offers.AreaxPosicion', to='offers.Position'),
        ),
        migrations.AddField(
            model_name='area',
            name='supervisorsArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.area'),
        ),
    ]
