# Generated by Django 3.1.3 on 2023-07-06 03:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaSesionXEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asistencia', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AsistenciaSesionXEmpleado',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='CursoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('duracion', models.DurationField(null=True)),
                ('suma_valoracionees', models.IntegerField(default=0)),
                ('cant_valoraciones', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CursoGeneral',
            },
        ),
        migrations.CreateModel(
            name='CursoGeneralXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.IntegerField()),
                ('cant_intentos_max', models.IntegerField(default=3)),
                ('porcentaje_asistencia_aprobacion', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'CursoGeneralXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='DocumentoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.TextField()),
            ],
            options={
                'db_table': 'DocumentoExamen',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.TextField()),
            ],
            options={
                'db_table': 'DocumentosRespuesta',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(default=0)),
                ('comentario', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'EmpleadoXCurso',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXCursoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentajeProgreso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_sesiones', models.IntegerField(default=0)),
                ('fechaAsignacion', models.DateTimeField(null=True)),
                ('fechaLimite', models.DateTimeField(null=True)),
                ('fechaCompletado', models.DateTimeField(null=True)),
                ('porcentaje_asistencia_aprobacion', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'EmpleadoXCursoEmpresa',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXCursoXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('0', 'Sin iniciar'), ('1', 'En progreso'), ('2', 'Completado, sin evaluar'), ('3', 'Completado, evaluado'), ('4', 'Desaprobado')], max_length=30)),
                ('nota_final', models.IntegerField(default=0)),
                ('cant_intentos', models.IntegerField(default=0)),
                ('fecha_evaluacion', models.DateTimeField(null=True)),
                ('ultima_evaluacion', models.BooleanField(default=False)),
                ('porcentajeProgreso', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cantidad_sesiones', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'EmpleadoXCursoXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Sin iniciar'), ('1', 'En progreso'), ('2', 'Completado, sin evaluar'), ('3', 'Completado, evaluado'), ('4', 'Desaprobado')], max_length=30)),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('valoracion', models.IntegerField(default=0)),
                ('comentario_valoracion', models.TextField(null=True)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_limite', models.DateTimeField(null=True)),
                ('fecha_completado', models.DateTimeField(null=True)),
                ('cantidad_cursos', models.IntegerField(default=0)),
                ('rubrica_calificada_evaluacion', models.JSONField(null=True)),
                ('nota_evaluacion', models.IntegerField(null=True)),
                ('comentario_evaluacion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'EmpleadoXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=300)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.categoria')),
            ],
            options={
                'db_table': 'Habilidad',
            },
        ),
        migrations.CreateModel(
            name='HabilidadXProveedorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.habilidad')),
            ],
            options={
                'db_table': 'HabilidadXProveedorUsuario',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('url_foto', models.TextField(null=True)),
                ('suma_valoraciones', models.IntegerField(default=0)),
                ('cant_valoraciones', models.IntegerField(default=0)),
                ('cant_empleados', models.IntegerField(default=0)),
                ('horas_duracion', models.DurationField(default=datetime.timedelta(0))),
                ('cant_intentos_cursos_max', models.IntegerField()),
                ('cant_intentos_evaluacion_integral_max', models.IntegerField()),
                ('estado', models.CharField(choices=[('0', 'Desactivado'), ('1', 'Creado sin Formulario'), ('2', 'Error formulario'), ('3', 'Creado completo')], default='0', max_length=1)),
                ('cantidad_cursos', models.IntegerField(default=0)),
                ('descripcion_evaluacion', models.TextField(null=True)),
                ('rubrica', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'LearningPath',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_maxima', models.IntegerField()),
                ('nota_minima', models.IntegerField()),
                ('numero_intentos_curso', models.IntegerField()),
                ('numero_intentos_lp', models.IntegerField()),
                ('num_preg_min_aprobar_curso_udemy', models.IntegerField()),
                ('num_preg_eval_udemy', models.IntegerField()),
            ],
            options={
                'db_table': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='ProveedorEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.categoria')),
            ],
            options={
                'db_table': 'ProveedorEmpresa',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateTimeField(null=True)),
                ('fecha_limite', models.DateTimeField(null=True)),
                ('url_video', models.TextField(null=True)),
                ('ubicacion', models.CharField(max_length=400, null=True)),
                ('aforo_maximo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Sesion',
            },
        ),
        migrations.CreateModel(
            name='CursoEmpresa',
            fields=[
                ('cursogeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='capacitaciones.cursogeneral')),
                ('tipo', models.CharField(choices=[('P', 'Presencial'), ('S', 'Virtual sincrono'), ('A', 'Virtual asincrono')], max_length=1)),
                ('es_libre', models.BooleanField(default=False)),
                ('url_foto', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_primera_sesion', models.DateTimeField(null=True)),
                ('fecha_ultima_sesion', models.DateTimeField(null=True)),
                ('cantidad_empleados', models.IntegerField(default=0)),
                ('porcentaje_asistencia_aprobacion', models.IntegerField(default=100)),
                ('cantidad_sesiones', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CursoEmpresa',
            },
            bases=('capacitaciones.cursogeneral',),
        ),
        migrations.CreateModel(
            name='CursoUdemy',
            fields=[
                ('cursogeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='capacitaciones.cursogeneral')),
                ('udemy_id', models.IntegerField()),
                ('course_udemy_detail', models.JSONField()),
                ('preguntas', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('0', 'Creado sin Formulario'), ('1', 'Formulario por confirmar'), ('2', 'Error formulario'), ('3', 'Creado completo')], default='0', max_length=1)),
            ],
            options={
                'db_table': 'CursoUdemy',
            },
            bases=('capacitaciones.cursogeneral',),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.sesion')),
            ],
            options={
                'db_table': 'Tema',
            },
        ),
        migrations.CreateModel(
            name='SesionXReponsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.sesion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorempresa')),
            ],
            options={
                'db_table': 'SesionXReponsable',
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='sesion_x_responsable',
            field=models.ManyToManyField(through='capacitaciones.SesionXReponsable', to='capacitaciones.ProveedorEmpresa'),
        ),
        migrations.CreateModel(
            name='ProveedorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorempresa')),
                ('habilidad_x_proveedor_usuario', models.ManyToManyField(through='capacitaciones.HabilidadXProveedorUsuario', to='capacitaciones.Habilidad')),
            ],
            options={
                'db_table': 'ProveedorUsuario',
            },
        ),
        migrations.AddField(
            model_name='habilidadxproveedorusuario',
            name='proveedor_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorusuario'),
        ),
    ]
