# Generated by Django 3.1.3 on 2023-05-25 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=1000)),
                ('respuesta_correcta', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Alternativa',
            },
        ),
        migrations.CreateModel(
            name='CursoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
                ('duracion', models.DurationField()),
                ('suma_valoracionees', models.IntegerField(default=0)),
                ('cant_valoraciones', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'CursoGeneral',
            },
        ),
        migrations.CreateModel(
            name='DetalleRubricaExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio_evaluacion', models.CharField(max_length=200)),
                ('nota_maxima', models.IntegerField()),
            ],
            options={
                'db_table': 'DetalleRubricaExamen',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('url_foto', models.TextField(null=True)),
                ('suma_valoraciones', models.IntegerField(default=0)),
                ('cant_valoraciones', models.IntegerField(default=0)),
                ('cant_empleados', models.IntegerField(default=0)),
                ('horas_duracion', models.DurationField(default=datetime.timedelta(0))),
                ('estado', models.CharField(choices=[('0', 'Desactivado'), ('1', 'CreadoSinFormulario'), ('2', 'ErrorFormulario'), ('3', 'CreadoCompleto')], default='0', max_length=1)),
            ],
            options={
                'db_table': 'LearningPath',
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_maxima', models.IntegerField()),
                ('nota_minima', models.IntegerField()),
                ('numero_intentos_curso', models.IntegerField()),
            ],
            options={
                'db_table': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Pregunta',
            },
        ),
        migrations.CreateModel(
            name='RubricaExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'RubricaExamen',
            },
        ),
        migrations.CreateModel(
            name='CursoUdemy',
            fields=[
                ('cursogeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='capacitaciones.cursogeneral')),
                ('udemy_id', models.IntegerField()),
                ('course_udemy_detail', models.JSONField()),
            ],
            options={
                'db_table': 'CursoUdemy',
            },
            bases=('capacitaciones.cursogeneral',),
        ),
        migrations.CreateModel(
            name='RubricaExamenXEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('rubrica_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.rubricaexamen')),
            ],
            options={
                'db_table': 'RubricaExamenXEmpleado',
            },
        ),
        migrations.AddField(
            model_name='rubricaexamen',
            name='rubrica_examen_x_empleado',
            field=models.ManyToManyField(through='capacitaciones.RubricaExamenXEmpleado', to='login.Employee'),
        ),
        migrations.CreateModel(
            name='EmpleadoXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Sin iniciar', 'Sin iniciar'), ('Completado', 'Completado'), ('En progreso', 'En progreso'), ('Caducado', 'Caducado'), ('Desaprobado', 'Desaprobado')], max_length=30)),
                ('porcentaje_progreso', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('apreciacion', models.TextField()),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'EmpleadoXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXCursoXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('estado', models.CharField(choices=[('Sin iniciar', 'Sin iniciar'), ('Completado', 'Completado'), ('En progreso', 'En progreso'), ('Sin evaluar', 'Sin evaluar'), ('Desaprobado', 'Desaprobado')], max_length=30)),
                ('nota_final', models.IntegerField()),
                ('cant_intentos', models.IntegerField(default=0)),
                ('fecha_evaluacion', models.DateTimeField()),
                ('ultima_evaluacion', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'EmpleadoXCursoXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoXCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
            options={
                'db_table': 'EmpleadoXCurso',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.TextField()),
                ('empleado_learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.empleadoxlearningpath')),
            ],
            options={
                'db_table': 'DocumentosRespuesta',
            },
        ),
        migrations.CreateModel(
            name='DocumentoExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_documento', models.TextField()),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'DocumentoExamen',
            },
        ),
        migrations.CreateModel(
            name='DetalleRubricaExamenXEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('detalle_rubrica_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.detallerubricaexamen')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
            options={
                'db_table': 'DetalleRubricaExamenXEmpleado',
            },
        ),
        migrations.AddField(
            model_name='detallerubricaexamen',
            name='detalle_rubrica_x_empleado',
            field=models.ManyToManyField(through='capacitaciones.DetalleRubricaExamenXEmpleado', to='login.Employee'),
        ),
        migrations.AddField(
            model_name='detallerubricaexamen',
            name='rubrica_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.rubricaexamen'),
        ),
        migrations.CreateModel(
            name='CursoGeneralXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_orden', models.IntegerField()),
                ('cant_intentos_max', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'CursoGeneralXLearningPath',
            },
        ),
        migrations.AddField(
            model_name='cursogeneral',
            name='curso_x_learning_path',
            field=models.ManyToManyField(through='capacitaciones.CursoGeneralXLearningPath', to='capacitaciones.LearningPath'),
        ),
        migrations.CreateModel(
            name='AsistenciaCursoEmpresaXEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asistencia', models.CharField(choices=[('P', 'Asistio puntual'), ('T', 'Asistio tarde'), ('N', 'No asistio'), ('J', 'Falta justificada')], max_length=1)),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
            ],
            options={
                'db_table': 'AsistenciaCursoEmpresaXEmpleado',
            },
        ),
        migrations.CreateModel(
            name='PreguntaXCursoUdemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.pregunta')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoudemy')),
            ],
            options={
                'db_table': 'PreguntaXCursoUdemy',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta_x_curso',
            field=models.ManyToManyField(through='capacitaciones.PreguntaXCursoUdemy', to='capacitaciones.CursoUdemy'),
        ),
        migrations.CreateModel(
            name='EmpleadoXCursoXPreguntaXAlternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.alternativa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.pregunta')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoudemy')),
            ],
            options={
                'db_table': 'EmpleadoXCursoXPreguntaXAlternativa',
            },
        ),
        migrations.CreateModel(
            name='CursoEmpresa',
            fields=[
                ('cursogeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='capacitaciones.cursogeneral')),
                ('tipo', models.CharField(choices=[('P', 'Presencial'), ('S', 'Virtual sincrono'), ('A', 'Virtual asincrono')], max_length=1)),
                ('asunto', models.TextField()),
                ('ubicacion', models.CharField(max_length=500, null=True)),
                ('fecha', models.DateTimeField()),
                ('url_video', models.TextField()),
                ('asistencia_x_empleado', models.ManyToManyField(through='capacitaciones.AsistenciaCursoEmpresaXEmpleado', to='login.Employee')),
            ],
            options={
                'db_table': 'CursoEmpresa',
            },
            bases=('capacitaciones.cursogeneral',),
        ),
        migrations.AddField(
            model_name='asistenciacursoempresaxempleado',
            name='curso_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoempresa'),
        ),
    ]
