# Generated by Django 3.1.3 on 2023-05-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningpath',
            old_name='cant_valores',
            new_name='cant_valoraciones',
        ),
    ]
