# Generated by Django 3.1.3 on 2023-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursogeneralxlearningpath',
            name='porcentaje_asistencia_aprobacion',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='cant_intentos_cursos_max',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
