# Generated by Django 3.1.3 on 2023-05-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='ubicacion',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
