# Generated by Django 3.1.3 on 2023-05-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Habilidad',
            },
        ),
        migrations.CreateModel(
            name='HabilidadXProveedorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'HabilidadXProveedorUsuario',
            },
        ),
        migrations.CreateModel(
            name='ProveedorEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.categoria')),
            ],
            options={
                'db_table': 'ProveedorEmpresa',
            },
        ),
        migrations.CreateModel(
            name='ProveedorUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorempresa')),
                ('habilidad_x_proveedor_usuario', models.ManyToManyField(through='capacitaciones.HabilidadXProveedorUsuario', to='capacitaciones.Habilidad')),
            ],
            options={
                'db_table': 'ProveedorUsuario',
            },
        ),
        migrations.AddField(
            model_name='habilidadxproveedorusuario',
            name='empreproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorusuario'),
        ),
        migrations.AddField(
            model_name='habilidadxproveedorusuario',
            name='habilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.habilidad'),
        ),
    ]
