# Generated by Django 3.1.3 on 2023-07-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath'),
        ),
        migrations.AddField(
            model_name='empleadoxcursoxlearningpath',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral'),
        ),
        migrations.AddField(
            model_name='empleadoxcursoxlearningpath',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='empleadoxcursoxlearningpath',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath'),
        ),
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='empleadoxcurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral'),
        ),
        migrations.AddField(
            model_name='empleadoxcurso',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='documentorespuesta',
            name='empleado_learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.empleadoxlearningpath'),
        ),
        migrations.AddField(
            model_name='documentoexamen',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath'),
        ),
        migrations.AddField(
            model_name='cursogeneralxlearningpath',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral'),
        ),
        migrations.AddField(
            model_name='cursogeneralxlearningpath',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath'),
        ),
        migrations.AddField(
            model_name='cursogeneral',
            name='curso_x_employee',
            field=models.ManyToManyField(through='capacitaciones.EmpleadoXCurso', to='login.Employee'),
        ),
        migrations.AddField(
            model_name='cursogeneral',
            name='curso_x_learning_path',
            field=models.ManyToManyField(through='capacitaciones.CursoGeneralXLearningPath', to='capacitaciones.LearningPath'),
        ),
        migrations.AddField(
            model_name='asistenciasesionxempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='asistenciasesionxempleado',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.sesion'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='cursoEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoempresa'),
        ),
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='cursoEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoempresa'),
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='curso_empresa_x_empleado',
            field=models.ManyToManyField(through='capacitaciones.EmpleadoXCursoEmpresa', to='login.Employee'),
        ),
        migrations.AddField(
            model_name='asistenciasesionxempleado',
            name='curso_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursoempresa'),
        ),
    ]
