# Generated by Django 3.1.3 on 2023-05-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoempresa',
            name='es_libre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cursogeneral',
            name='duracion',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='aforo_maximo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha_limite',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='ubicacion',
            field=models.CharField(choices=[('Auditorio primer piso', 'Auditorio primer piso'), ('Auditorio segundo piso', 'Auditorio segundo piso'), ('Auditorio tercer piso', 'Auditorio tercer piso'), ('Auditorio cuarto piso', 'Auditorio cuarto piso'), ('Auditorio quinto piso', 'Auditorio quinto piso')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='url_video',
            field=models.TextField(null=True),
        ),
    ]
