# Generated by Django 3.1.3 on 2023-06-01 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230527_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistenciasesionxempleado',
            name='sesion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.sesion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='porcentaje_asistencia_aprobacion',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='porcentaje_asistencia_aprobacion',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='fecha_completado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asistenciasesionxempleado',
            name='estado_asistencia',
            field=models.CharField(choices=[('P', 'Asistió puntual'), ('T', 'Asistió tarde'), ('N', 'No asistió'), ('J', 'Falta justificada')], max_length=1),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoempresa',
            name='apreciacion',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoempresa',
            name='fechaAsignacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoempresa',
            name='fechaCompletado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoempresa',
            name='fechaLimite',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoxlearningpath',
            name='estado',
            field=models.CharField(choices=[('0', 'Sin iniciar'), ('1', 'En progreso'), ('2', 'Completado, sin evaluar'), ('3', 'Completado, evaluado'), ('4', 'Desaprobado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='empleadoxlearningpath',
            name='fecha_asignacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxlearningpath',
            name='fecha_limite',
            field=models.DateTimeField(null=True),
        ),
    ]
