# Generated by Django 3.1.3 on 2023-05-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230526_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='cant_intentos_evaluacion_integral_max',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametros',
            name='numero_intentos_lp',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
