# Generated by Django 3.1.3 on 2023-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230526_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidadxproveedorusuario',
            old_name='empreproveedor',
            new_name='proveedor_usuario',
        ),
        migrations.AlterField(
            model_name='proveedorusuario',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
