# Generated by Django 3.1.3 on 2023-07-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0002_auto_20230705_2220'),
        ('capacitaciones', '0002_auto_20230705_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciasXLearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
            options={
                'db_table': 'CompetenciasXLearningPath',
            },
        ),
        migrations.CreateModel(
            name='CompetenciasXCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral')),
            ],
            options={
                'db_table': 'CompetenciasXCurso',
            },
        ),
    ]
