# Generated by Django 3.1.3 on 2023-05-11 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230507_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoempresa',
            name='ubicacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='estado',
            field=models.CharField(choices=[('0', 'Desactivado'), ('1', 'CreadoSinFormulario'), ('2', 'ErrorFormulario'), ('3', 'CreadoCompleto')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='horas_duracion',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='url_foto',
            field=models.TextField(null=True),
        ),
    ]
