# Generated by Django 3.1.3 on 2023-06-03 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230602_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.categoria'),
            preserve_default=False,
        ),
    ]
