# Generated by Django 3.1.3 on 2023-05-26 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_auto_20230526_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoempresa',
            old_name='banderaL',
            new_name='es_libre',
        ),
    ]
