# Generated by Django 3.1.3 on 2023-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_competenciasxcurso_competenciasxlearningpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoempresa',
            name='preguntas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='empleadoxcurso',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
    ]
