# Generated by Django 3.1.3 on 2023-05-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_auto_20230526_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='clase',
            new_name='sesion',
        ),
    ]
