# Generated by Django 3.1.3 on 2023-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_habilidad_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciasesionxempleado',
            name='estado_asistencia',
            field=models.BooleanField(),
        ),
    ]
