# Generated by Django 3.1.3 on 2023-06-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0003_auto_20230531_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sesion_x_responsable',
            field=models.ManyToManyField(through='capacitaciones.SesionXReponsable', to='capacitaciones.ProveedorEmpresa'),
        ),
        migrations.AlterField(
            model_name='sesionxreponsable',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.proveedorempresa'),
        ),
    ]
