# Generated by Django 3.1.3 on 2023-05-27 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0004_auto_20230527_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursogeneral',
            name='cantidad_empleados',
        ),
        migrations.RemoveField(
            model_name='cursogeneral',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='cursogeneral',
            name='fecha_primera_sesion',
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='cantidad_empleados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='fecha_primera_sesion',
            field=models.DateTimeField(null=True),
        ),
    ]
