# Generated by Django 3.1.3 on 2023-07-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0004_auto_20230712_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='estado',
            field=models.CharField(choices=[('0', 'Sin empezar'), ('1', 'Finalizado sin evaluar'), ('2', 'Finalizado evaluado ')], default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='empleadoxlearningpath',
            name='estado',
            field=models.CharField(choices=[('0', 'Sin iniciar'), ('1', 'En progreso'), ('2', 'Completado, sin rendir'), ('3', 'Completado, sin evaluar'), ('4', 'Completado, evaluado'), ('5', 'Desaprobado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='nota_maxima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='nota_minima',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='num_preg_eval_udemy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='num_preg_min_aprobar_curso_udemy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='numero_intentos_curso',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parametros',
            name='numero_intentos_lp',
            field=models.IntegerField(null=True),
        ),
    ]
