# Generated by Django 3.1.3 on 2023-05-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0004_auto_20230526_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursogeneral',
            name='enlace_ec2',
        ),
        migrations.RemoveField(
            model_name='cursogeneral',
            name='foto',
        ),
        migrations.AddField(
            model_name='cursoempresa',
            name='url_foto',
            field=models.TextField(null=True),
        ),
    ]
