# Generated by Django 3.1.3 on 2023-06-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0005_auto_20230602_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoxcursoempresa',
            name='porcentajeProgreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
