# Generated by Django 3.1.3 on 2023-06-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0006_auto_20230603_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoempresa',
            name='fecha_ultima_sesion',
            field=models.DateTimeField(null=True),
        ),
    ]
