# Generated by Django 3.1.3 on 2023-06-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0007_cursoempresa_fecha_ultima_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoxcursoxpreguntaxalternativa',
            name='alternativa',
        ),
        migrations.RemoveField(
            model_name='empleadoxcursoxpreguntaxalternativa',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='empleadoxcursoxpreguntaxalternativa',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='empleadoxcursoxpreguntaxalternativa',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='pregunta_x_curso',
        ),
        migrations.RemoveField(
            model_name='preguntaxcursoudemy',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='preguntaxcursoudemy',
            name='pregunta',
        ),
        migrations.AddField(
            model_name='cursoudemy',
            name='estado',
            field=models.CharField(choices=[('0', 'Creado sin Formulario'), ('1', 'Formulario por confirmar'), ('2', 'Error formulario'), ('3', 'Creado completo')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='cursoudemy',
            name='preguntas',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Alternativa',
        ),
        migrations.DeleteModel(
            name='EmpleadoXCursoXPreguntaXAlternativa',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='PreguntaXCursoUdemy',
        ),
    ]
