# Generated by Django 3.1.3 on 2023-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0009_auto_20230605_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoudemy',
            name='preguntas',
            field=models.JSONField(default={}),
        ),
    ]
