# Generated by Django 3.1.3 on 2023-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0011_auto_20230606_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoxcursoxlearningpath',
            name='progreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
