# Generated by Django 3.1.3 on 2023-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0012_auto_20230607_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoxcurso',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoxlearningpath',
            name='fecha_evaluacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoxlearningpath',
            name='nota_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='empleadoxcursoxlearningpath',
            name='ultima_evaluacion',
            field=models.BooleanField(default=False),
        ),
    ]
