# Generated by Django 3.1.3 on 2023-06-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0013_auto_20230607_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoempresa',
            name='cantidad_sesiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleadoxcursoempresa',
            name='cantidad_sesiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleadoxcursoxlearningpath',
            name='cantidad_sesiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleadoxcursoxlearningpath',
            name='porcentajeProgreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='cantidad_cursos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='cantidad_cursos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cursogeneralxlearningpath',
            name='cant_intentos_max',
            field=models.IntegerField(default=3),
        ),
    ]
