# Generated by Django 3.1.3 on 2023-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0014_auto_20230611_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='num_preg_eval_udemy',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametros',
            name='num_preg_min_aprobar_curso_udemy',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
