# Generated by Django 3.1.3 on 2023-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0016_auto_20230615_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='comentario_evaluacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='nota_evaluacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='rubrica_calificada_evaluacion',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='descripcion_evaluacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='rubrica',
            field=models.JSONField(null=True),
        ),
    ]
