# Generated by Django 3.1.3 on 2023-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0017_auto_20230615_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoxcursoempresa',
            name='apreciacion',
        ),
        migrations.AddField(
            model_name='empleadoxcurso',
            name='apreciacion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
