# Generated by Django 3.1.3 on 2023-06-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0018_auto_20230618_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleadoxcurso',
            old_name='apreciacion',
            new_name='comentario',
        ),
    ]
