# Generated by Django 3.1.3 on 2023-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0019_auto_20230618_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleadoxlearningpath',
            old_name='apreciacion',
            new_name='comentario_valoracion',
        ),
        migrations.AddField(
            model_name='empleadoxlearningpath',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
