# Generated by Django 3.1.3 on 2023-06-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('benefits', models.TextField(blank=True, default='')),
                ('responsabilities', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('tipoJornada', models.TextField(blank=True, default='')),
                ('modalidadTrabajo', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AreaxPosicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('availableQuantity', models.IntegerField()),
                ('unavailableQuantity', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.area')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.position')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='roles',
            field=models.ManyToManyField(through='personal.AreaxPosicion', to='personal.Position'),
        ),
        migrations.AddField(
            model_name='area',
            name='supervisorsArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.area'),
        ),
    ]
