# Generated by Django 3.1.3 on 2023-07-06 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaxPosicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('availableQuantity', models.IntegerField(default=0)),
                ('unavailableQuantity', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.area')),
            ],
        ),
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('available_positions_quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion')),
            ],
            options={
                'db_table': 'ProcesoSeleccion',
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('introduction', models.TextField(blank=True, default='')),
                ('offer_introduction', models.TextField(blank=True, default='')),
                ('responsabilities_introduction', models.TextField(blank=True, default='')),
                ('capacities_introduction', models.TextField(blank=True, default='')),
                ('beneficies_introduction', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_url', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('salary_range', models.TextField(blank=True, default='')),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.hiringprocess')),
            ],
            options={
                'db_table': 'OfertaLaboral',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('benefits', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('tipoJornada', models.TextField(blank=True, default='', null=True)),
                ('modalidadTrabajo', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'TipoEtapa',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingxLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.traininglevel')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingxAreaxPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('areaxposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.trainingxlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='training',
            name='levels',
            field=models.ManyToManyField(through='personal.TrainingxLevel', to='personal.TrainingLevel'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.trainingtype'),
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position_similarity', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_stages', to='personal.hiringprocess')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.stagetype')),
            ],
            options={
                'db_table': 'EtapaProceso',
            },
        ),
        migrations.CreateModel(
            name='JobOfferNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent', models.BooleanField(default=False)),
                ('suitable', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.joboffer')),
            ],
            options={
                'db_table': 'NotificacionLaboral',
            },
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('areaxposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeXHiringProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.hiringprocess')),
            ],
            options={
                'db_table': 'EmpleadoXProcesoSeleccion',
            },
        ),
        migrations.AddField(
            model_name='areaxposicion',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.position'),
        ),
        migrations.AddField(
            model_name='area',
            name='positions',
            field=models.ManyToManyField(through='personal.AreaxPosicion', to='personal.Position'),
        ),
        migrations.AddField(
            model_name='area',
            name='supervisorsArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.area'),
        ),
    ]
