# Generated by Django 3.1.3 on 2023-06-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('available_positions_quantity', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.position')),
            ],
        ),
    ]
