# Generated by Django 3.1.3 on 2023-06-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('introduction', models.TextField(blank=True, default='')),
                ('offer_introduction', models.TextField(blank=True, default='')),
                ('responsabilities_introduction', models.TextField(blank=True, default='')),
                ('capacities_introduction', models.TextField(blank=True, default='')),
                ('beneficies_introduction', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_url', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, default='')),
                ('salary_range', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'OfertaLaboral',
            },
        ),
        migrations.RemoveField(
            model_name='position',
            name='responsabilities',
        ),
        migrations.AddField(
            model_name='hiringprocess',
            name='name',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='supervisorsArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.area'),
        ),
        migrations.AlterField(
            model_name='areaxposicion',
            name='availableQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='areaxposicion',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='areaxposicion',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='areaxposicion',
            name='unavailableQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hiringprocess',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion'),
        ),
        migrations.AlterField(
            model_name='position',
            name='benefits',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='modalidadTrabajo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='tipoJornada',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='hiring_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_stages', to='personal.hiringprocess'),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='JobOfferNotification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent', models.BooleanField(default=False)),
                ('suitable', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.joboffer')),
            ],
            options={
                'db_table': 'NotificacionLaboral',
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='hiring_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.hiringprocess'),
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.area')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.position')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeXHiringProcess',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.hiringprocess')),
            ],
            options={
                'db_table': 'EmpleadoXProcesoSeleccion',
            },
        ),
    ]
