# Generated by Django 3.1.3 on 2023-06-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_hiringprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringprocess',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='hiringprocess',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hiringprocess',
            name='modified_date',
        ),
    ]
