# Generated by Django 3.1.3 on 2023-07-13 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0001_initial'),
        ('personal', '0002_auto_20230713_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('competency_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.competencyxapplicant')),
            ],
        ),
    ]
