# Generated by Django 3.1.3 on 2023-06-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20230601_1634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hiringprocess',
            table='ProcesoSeleccion',
        ),
    ]
