# Generated by Django 3.1.3 on 2023-06-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20230601_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'TipoEtapa',
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('hiring_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.hiringprocess')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.stagetype')),
            ],
            options={
                'db_table': 'EtapaProceso',
            },
        ),
    ]
