# Generated by Django 3.1.3 on 2023-06-01 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_processstage_stagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringprocess',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiringprocess',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hiringprocess',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
