# Generated by Django 3.1.3 on 2023-06-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20230601_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='benefits',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='modalidadTrabajo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='responsabilities',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='tipoJornada',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='hiring_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_stages', to='personal.hiringprocess'),
        ),
        migrations.AlterField(
            model_name='processstage',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.area')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.position')),
            ],
        ),
    ]
