# Generated by Django 3.1.3 on 2023-06-22 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_auto_20230622_1238'),
        ('capacitaciones', '0020_auto_20230619_0019'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('evaluationDate', models.DateTimeField(null=True)),
                ('hasComment', models.BooleanField()),
                ('generalComment', models.CharField(blank=True, max_length=500, null=True)),
                ('isFinished', models.BooleanField()),
                ('finalScore', models.FloatField(blank=True, null=True)),
                ('proyecto', models.TextField(blank=True, default='')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.area')),
                ('evaluated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluated', to='login.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('evaluationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.category')),
            ],
            options={
                'db_table': 'Competence',
            },
        ),
        migrations.CreateModel(
            name='PlantillaxSubCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.plantilla')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationxSubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('hasComment', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluator', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.position'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='relatedEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation'),
        ),
        migrations.CreateModel(
            name='CompetencessXEmployeeXLearningPath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isInitial', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('isActual', models.BooleanField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, default='', null=True)),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluation')),
                ('lp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluationtype'),
        ),
    ]
