# Generated by Django 3.1.3 on 2023-05-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('evaluationDate', models.DateTimeField()),
                ('hasComment', models.BooleanField()),
                ('generalComment', models.CharField(blank=True, max_length=500, null=True)),
                ('isFinished', models.BooleanField()),
                ('finalScore', models.FloatField(blank=True, null=True)),
                ('proyecto', models.TextField(blank=True, default='')),
                ('areaxPosicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.areaxposicion')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
                ('name', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.category')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationxSubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('hasComment', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory')),
            ],
        ),
    ]
