# Generated by Django 3.1.3 on 2023-07-06 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField()),
                ('modifiedDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencessXEmployeeXLearningPath',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isInitial', models.BooleanField(default=False)),
                ('level', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('scale', models.IntegerField(choices=[(0, 'de 0 a 20, no iniciado'), (1, 'de 21 a 40, en proceso'), (2, 'de 41 a 60, en proceso'), (3, 'de 61 a 80, en proceso'), (4, 'de 81 a 100, en proceso')], default=2)),
                ('scaleRequired', models.IntegerField(blank=True, choices=[(0, 'de 0 a 20, no iniciado'), (1, 'de 21 a 40, en proceso'), (2, 'de 41 a 60, en proceso'), (3, 'de 61 a 80, en proceso'), (4, 'de 81 a 100, en proceso')], default=2, null=True)),
                ('levelGap', models.IntegerField(blank=True, null=True)),
                ('likeness', models.FloatField(blank=True, null=True)),
                ('hasCertificate', models.BooleanField(blank=True, default=False, null=True)),
                ('registerByEmployee', models.BooleanField(blank=True, default=False, null=True)),
                ('requiredForPosition', models.BooleanField(blank=True, default=False, null=True)),
                ('isActual', models.BooleanField(blank=True, null=True)),
                ('modifiedBy', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyxAreaxPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('scale', models.IntegerField(choices=[(0, 'de 0 a 20, no iniciado'), (1, 'de 21 a 40, en proceso'), (2, 'de 41 a 60, en proceso'), (3, 'de 61 a 80, en proceso'), (4, 'de 81 a 100, en proceso')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('evaluationDate', models.DateTimeField(null=True)),
                ('hasComment', models.BooleanField()),
                ('generalComment', models.CharField(blank=True, max_length=500, null=True)),
                ('isFinished', models.BooleanField()),
                ('finalScore', models.FloatField(blank=True, null=True)),
                ('proyecto', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('evaluationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Relacionado a aspectos técnicos'), (1, 'Relacionado a la persona')], default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.category')),
            ],
            options={
                'db_table': 'Competence',
            },
        ),
        migrations.CreateModel(
            name='PlantillaxSubCategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.plantilla')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationxSubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('hasComment', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation')),
                ('subCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory')),
            ],
        ),
    ]
