# Generated by Django 3.1.3 on 2023-05-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='supervisorsArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.area'),
        ),
    ]
