# Generated by Django 3.1.3 on 2023-07-06 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capacitaciones', '0002_auto_20230705_2220'),
        ('personal', '0001_initial'),
        ('login', '0001_initial'),
        ('evaluations_and_promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.area'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluated', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluator', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.position'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='relatedEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation'),
        ),
        migrations.AddField(
            model_name='competencyxareaxposition',
            name='areaxposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.areaxposicion'),
        ),
        migrations.AddField(
            model_name='competencyxareaxposition',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory'),
        ),
        migrations.AddField(
            model_name='competencessxemployeexlearningpath',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory'),
        ),
        migrations.AddField(
            model_name='competencessxemployeexlearningpath',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.cursogeneral'),
        ),
        migrations.AddField(
            model_name='competencessxemployeexlearningpath',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.employee'),
        ),
        migrations.AddField(
            model_name='competencessxemployeexlearningpath',
            name='evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluation'),
        ),
        migrations.AddField(
            model_name='competencessxemployeexlearningpath',
            name='lp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.learningpath'),
        ),
        migrations.AddField(
            model_name='category',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluationtype'),
        ),
    ]
