# Generated by Django 3.1.3 on 2023-05-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('evaluations_and_promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluated', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluator', to='login.employee'),
        ),
    ]
