# Generated by Django 3.1.3 on 2023-05-23 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230523_1358'),
        ('personal', '0001_initial'),
        ('evaluations_and_promotions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='category',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluated', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Evaluator', to='login.employee'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='proyecto',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='areaxPosicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.areaxposicion'),
        ),
        migrations.DeleteModel(
            name='AreaxPosicion',
        ),
    ]
