# Generated by Django 3.1.3 on 2023-07-13 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230705_2220'),
        ('evaluations_and_promotions', '0002_auto_20230705_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='evaluationType',
        ),
        migrations.CreateModel(
            name='CompetencyxApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('scale', models.IntegerField(choices=[(0, 'de 0 a 20, no iniciado'), (1, 'de 21 a 40, en proceso'), (2, 'de 41 a 60, en proceso'), (3, 'de 61 a 80, en proceso'), (4, 'de 81 a 100, en proceso')], default=2)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.applicant')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluations_and_promotions.subcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
