# Generated by Django 3.1.3 on 2023-05-04 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0003_auto_20230501_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationxSubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modifiedDate', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('hasComment', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('score', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('modifiedDate', models.DateField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryType',
        ),
        migrations.RemoveField(
            model_name='category',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hasComment',
        ),
        migrations.RemoveField(
            model_name='category',
            name='hasScore',
        ),
        migrations.RemoveField(
            model_name='category',
            name='score',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='evaluationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluationtype'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='areaxPosicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.areaxposicion'),
        ),
        migrations.AlterField(
            model_name='area',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='area',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='areaxposicion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluationtype',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evaluationtype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evaluationtype',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluationtype',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='position',
            name='benefits',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='position',
            name='creationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='position',
            name='modalidadTrabajo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='position',
            name='modifiedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='responsabilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='position',
            name='tipoJornada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.category'),
        ),
        migrations.AddField(
            model_name='evaluationxsubcategory',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationxsubcategory',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluations_and_promotions.subcategory'),
        ),
    ]
