# Generated by Django 3.1.3 on 2023-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations_and_promotions', '0004_auto_20230503_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
